# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publisherdialog_hor.ui'
#
# Created: Thu Jul  8 17:18:55 2010
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PublisherDialog(object):
    def setupUi(self, PublisherDialog):
        PublisherDialog.setObjectName("PublisherDialog")
        PublisherDialog.resize(404, 153)
        self.gridLayout_2 = QtGui.QGridLayout(PublisherDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.basePath = QtGui.QLineEdit(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basePath.sizePolicy().hasHeightForWidth())
        self.basePath.setSizePolicy(sizePolicy)
        self.basePath.setObjectName("basePath")
        self.gridLayout_2.addWidget(self.basePath, 0, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_2.addWidget(self.connectButton, 0, 2, 1, 2)
        self.setters = QtGui.QWidget(PublisherDialog)
        self.setters.setObjectName("setters")
        self.gridLayout = QtGui.QGridLayout(self.setters)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.intValue = QtGui.QSpinBox(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intValue.sizePolicy().hasHeightForWidth())
        self.intValue.setSizePolicy(sizePolicy)
        self.intValue.setObjectName("intValue")
        self.gridLayout.addWidget(self.intValue, 0, 1, 1, 1)
        self.unsetIntButton = QtGui.QPushButton(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unsetIntButton.sizePolicy().hasHeightForWidth())
        self.unsetIntButton.setSizePolicy(sizePolicy)
        self.unsetIntButton.setObjectName("unsetIntButton")
        self.gridLayout.addWidget(self.unsetIntButton, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.stringValue = QtGui.QLineEdit(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stringValue.sizePolicy().hasHeightForWidth())
        self.stringValue.setSizePolicy(sizePolicy)
        self.stringValue.setObjectName("stringValue")
        self.gridLayout.addWidget(self.stringValue, 1, 1, 1, 1)
        self.setStringButton = QtGui.QPushButton(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setStringButton.sizePolicy().hasHeightForWidth())
        self.setStringButton.setSizePolicy(sizePolicy)
        self.setStringButton.setObjectName("setStringButton")
        self.gridLayout.addWidget(self.setStringButton, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.byteArrayValue = QtGui.QLineEdit(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteArrayValue.sizePolicy().hasHeightForWidth())
        self.byteArrayValue.setSizePolicy(sizePolicy)
        self.byteArrayValue.setObjectName("byteArrayValue")
        self.gridLayout.addWidget(self.byteArrayValue, 2, 1, 1, 1)
        self.setByteArrayButton = QtGui.QPushButton(self.setters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setByteArrayButton.sizePolicy().hasHeightForWidth())
        self.setByteArrayButton.setSizePolicy(sizePolicy)
        self.setByteArrayButton.setObjectName("setByteArrayButton")
        self.gridLayout.addWidget(self.setByteArrayButton, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.setters, 1, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(20, 196, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(PublisherDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 2, 1, 1)
        self.label.setBuddy(self.basePath)
        self.label_2.setBuddy(self.intValue)
        self.label_3.setBuddy(self.stringValue)

        self.retranslateUi(PublisherDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PublisherDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PublisherDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PublisherDialog)
        PublisherDialog.setTabOrder(self.basePath, self.connectButton)
        PublisherDialog.setTabOrder(self.connectButton, self.intValue)
        PublisherDialog.setTabOrder(self.intValue, self.unsetIntButton)
        PublisherDialog.setTabOrder(self.unsetIntButton, self.stringValue)
        PublisherDialog.setTabOrder(self.stringValue, self.setStringButton)
        PublisherDialog.setTabOrder(self.setStringButton, self.byteArrayValue)
        PublisherDialog.setTabOrder(self.byteArrayValue, self.setByteArrayButton)
        PublisherDialog.setTabOrder(self.setByteArrayButton, self.buttonBox)

    def retranslateUi(self, PublisherDialog):
        PublisherDialog.setWindowTitle(QtGui.QApplication.translate("PublisherDialog", "Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PublisherDialog", "Base path:", None, QtGui.QApplication.UnicodeUTF8))
        self.basePath.setText(QtGui.QApplication.translate("PublisherDialog", "/example", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("PublisherDialog", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PublisherDialog", "intValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.unsetIntButton.setText(QtGui.QApplication.translate("PublisherDialog", "Unset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PublisherDialog", "stringValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.stringValue.setText(QtGui.QApplication.translate("PublisherDialog", "testString", None, QtGui.QApplication.UnicodeUTF8))
        self.setStringButton.setText(QtGui.QApplication.translate("PublisherDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PublisherDialog", "byteArrayValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.byteArrayValue.setText(QtGui.QApplication.translate("PublisherDialog", "testByteArray", None, QtGui.QApplication.UnicodeUTF8))
        self.setByteArrayButton.setText(QtGui.QApplication.translate("PublisherDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))

