# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publisherdialog.ui'
#
# Created: Thu Jul  8 17:18:03 2010
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PublisherDialog(object):
    def setupUi(self, PublisherDialog):
        PublisherDialog.setObjectName("PublisherDialog")
        PublisherDialog.resize(240, 338)
        self.gridLayout = QtGui.QGridLayout(PublisherDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(PublisherDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.basePath = QtGui.QLineEdit(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basePath.sizePolicy().hasHeightForWidth())
        self.basePath.setSizePolicy(sizePolicy)
        self.basePath.setObjectName("basePath")
        self.gridLayout.addWidget(self.basePath, 0, 2, 1, 1)
        self.setters = QtGui.QScrollArea(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setters.sizePolicy().hasHeightForWidth())
        self.setters.setSizePolicy(sizePolicy)
        self.setters.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setters.setWidgetResizable(True)
        self.setters.setObjectName("setters")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.setters)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 226, 238))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtGui.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setRowWrapPolicy(QtGui.QFormLayout.WrapLongRows)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.intValue = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intValue.sizePolicy().hasHeightForWidth())
        self.intValue.setSizePolicy(sizePolicy)
        self.intValue.setObjectName("intValue")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.intValue)
        self.unsetIntButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unsetIntButton.sizePolicy().hasHeightForWidth())
        self.unsetIntButton.setSizePolicy(sizePolicy)
        self.unsetIntButton.setObjectName("unsetIntButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.unsetIntButton)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.stringValue = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stringValue.sizePolicy().hasHeightForWidth())
        self.stringValue.setSizePolicy(sizePolicy)
        self.stringValue.setObjectName("stringValue")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.stringValue)
        self.setStringButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setStringButton.sizePolicy().hasHeightForWidth())
        self.setStringButton.setSizePolicy(sizePolicy)
        self.setStringButton.setObjectName("setStringButton")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.setStringButton)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.byteArrayValue = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteArrayValue.sizePolicy().hasHeightForWidth())
        self.byteArrayValue.setSizePolicy(sizePolicy)
        self.byteArrayValue.setObjectName("byteArrayValue")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.byteArrayValue)
        self.setByteArrayButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setByteArrayButton.sizePolicy().hasHeightForWidth())
        self.setByteArrayButton.setSizePolicy(sizePolicy)
        self.setByteArrayButton.setObjectName("setByteArrayButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.setByteArrayButton)
        self.setters.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.setters, 2, 1, 1, 2)
        self.connectButton = QtGui.QPushButton(PublisherDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 1, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(PublisherDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 2, 1, 1)
        self.label.setBuddy(self.basePath)
        self.label_2.setBuddy(self.intValue)
        self.label_3.setBuddy(self.stringValue)

        self.retranslateUi(PublisherDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PublisherDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PublisherDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PublisherDialog)
        PublisherDialog.setTabOrder(self.basePath, self.connectButton)
        PublisherDialog.setTabOrder(self.connectButton, self.setters)
        PublisherDialog.setTabOrder(self.setters, self.intValue)
        PublisherDialog.setTabOrder(self.intValue, self.unsetIntButton)
        PublisherDialog.setTabOrder(self.unsetIntButton, self.stringValue)
        PublisherDialog.setTabOrder(self.stringValue, self.setStringButton)
        PublisherDialog.setTabOrder(self.setStringButton, self.byteArrayValue)
        PublisherDialog.setTabOrder(self.byteArrayValue, self.setByteArrayButton)
        PublisherDialog.setTabOrder(self.setByteArrayButton, self.buttonBox)

    def retranslateUi(self, PublisherDialog):
        PublisherDialog.setWindowTitle(QtGui.QApplication.translate("PublisherDialog", "Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PublisherDialog", "Base path:", None, QtGui.QApplication.UnicodeUTF8))
        self.basePath.setText(QtGui.QApplication.translate("PublisherDialog", "/example", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PublisherDialog", "intValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.unsetIntButton.setText(QtGui.QApplication.translate("PublisherDialog", "Unset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PublisherDialog", "stringValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.stringValue.setText(QtGui.QApplication.translate("PublisherDialog", "testString", None, QtGui.QApplication.UnicodeUTF8))
        self.setStringButton.setText(QtGui.QApplication.translate("PublisherDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PublisherDialog", "byteArrayValue:", None, QtGui.QApplication.UnicodeUTF8))
        self.byteArrayValue.setText(QtGui.QApplication.translate("PublisherDialog", "testByteArray", None, QtGui.QApplication.UnicodeUTF8))
        self.setByteArrayButton.setText(QtGui.QApplication.translate("PublisherDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("PublisherDialog", "Connect", None, QtGui.QApplication.UnicodeUTF8))

