# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiodevicesbase.ui'
#
# Created: Mon Jul  5 19:07:00 2010
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AudioDevicesBase(object):
    def setupUi(self, AudioDevicesBase):
        AudioDevicesBase.setObjectName("AudioDevicesBase")
        AudioDevicesBase.resize(679, 598)
        self.centralwidget = QtGui.QWidget(AudioDevicesBase)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 558))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout_2.addWidget(self.modeLabel, 0, 0, 1, 1)
        self.deviceLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.deviceLabel.setObjectName("deviceLabel")
        self.gridLayout_2.addWidget(self.deviceLabel, 0, 1, 1, 1)
        self.modeBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.gridLayout_2.addWidget(self.modeBox, 1, 0, 1, 1)
        self.deviceBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.deviceBox.setObjectName("deviceBox")
        self.gridLayout_2.addWidget(self.deviceBox, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.testFormatTab = QtGui.QWidget()
        self.testFormatTab.setObjectName("testFormatTab")
        self.gridLayout = QtGui.QGridLayout(self.testFormatTab)
        self.gridLayout.setObjectName("gridLayout")
        self.actualLabel = QtGui.QLabel(self.testFormatTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actualLabel.sizePolicy().hasHeightForWidth())
        self.actualLabel.setSizePolicy(sizePolicy)
        self.actualLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.actualLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.actualLabel.setTextFormat(QtCore.Qt.RichText)
        self.actualLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actualLabel.setObjectName("actualLabel")
        self.gridLayout.addWidget(self.actualLabel, 0, 1, 1, 1)
        self.nearestLabel = QtGui.QLabel(self.testFormatTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearestLabel.sizePolicy().hasHeightForWidth())
        self.nearestLabel.setSizePolicy(sizePolicy)
        self.nearestLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.nearestLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.nearestLabel.setTextFormat(QtCore.Qt.RichText)
        self.nearestLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nearestLabel.setObjectName("nearestLabel")
        self.gridLayout.addWidget(self.nearestLabel, 0, 2, 1, 1)
        self.frequencyBox = QtGui.QComboBox(self.testFormatTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyBox.sizePolicy().hasHeightForWidth())
        self.frequencyBox.setSizePolicy(sizePolicy)
        self.frequencyBox.setObjectName("frequencyBox")
        self.gridLayout.addWidget(self.frequencyBox, 3, 1, 1, 1)
        self.nearestFreq = QtGui.QLineEdit(self.testFormatTab)
        self.nearestFreq.setEnabled(False)
        self.nearestFreq.setObjectName("nearestFreq")
        self.gridLayout.addWidget(self.nearestFreq, 3, 2, 1, 1)
        self.channelsBox = QtGui.QComboBox(self.testFormatTab)
        self.channelsBox.setObjectName("channelsBox")
        self.gridLayout.addWidget(self.channelsBox, 5, 1, 1, 1)
        self.nearestChannel = QtGui.QLineEdit(self.testFormatTab)
        self.nearestChannel.setEnabled(False)
        self.nearestChannel.setObjectName("nearestChannel")
        self.gridLayout.addWidget(self.nearestChannel, 5, 2, 1, 1)
        self.sampleSizesBox = QtGui.QComboBox(self.testFormatTab)
        self.sampleSizesBox.setObjectName("sampleSizesBox")
        self.gridLayout.addWidget(self.sampleSizesBox, 9, 1, 1, 1)
        self.nearestSampleSize = QtGui.QLineEdit(self.testFormatTab)
        self.nearestSampleSize.setEnabled(False)
        self.nearestSampleSize.setObjectName("nearestSampleSize")
        self.gridLayout.addWidget(self.nearestSampleSize, 9, 2, 1, 1)
        self.endianBox = QtGui.QComboBox(self.testFormatTab)
        self.endianBox.setObjectName("endianBox")
        self.gridLayout.addWidget(self.endianBox, 14, 1, 1, 1)
        self.nearestEndian = QtGui.QLineEdit(self.testFormatTab)
        self.nearestEndian.setEnabled(False)
        self.nearestEndian.setObjectName("nearestEndian")
        self.gridLayout.addWidget(self.nearestEndian, 14, 2, 1, 1)
        self.testButton = QtGui.QPushButton(self.testFormatTab)
        self.testButton.setObjectName("testButton")
        self.gridLayout.addWidget(self.testButton, 15, 1, 1, 1)
        self.testResult = QtGui.QLabel(self.testFormatTab)
        self.testResult.setObjectName("testResult")
        self.gridLayout.addWidget(self.testResult, 15, 2, 1, 1)
        self.actualFreqLabel = QtGui.QLabel(self.testFormatTab)
        self.actualFreqLabel.setObjectName("actualFreqLabel")
        self.gridLayout.addWidget(self.actualFreqLabel, 3, 0, 1, 1)
        self.actualChannelLabel = QtGui.QLabel(self.testFormatTab)
        self.actualChannelLabel.setObjectName("actualChannelLabel")
        self.gridLayout.addWidget(self.actualChannelLabel, 5, 0, 1, 1)
        self.actualSampleSizeLabel = QtGui.QLabel(self.testFormatTab)
        self.actualSampleSizeLabel.setObjectName("actualSampleSizeLabel")
        self.gridLayout.addWidget(self.actualSampleSizeLabel, 9, 0, 1, 1)
        self.actualEndianLabel = QtGui.QLabel(self.testFormatTab)
        self.actualEndianLabel.setObjectName("actualEndianLabel")
        self.gridLayout.addWidget(self.actualEndianLabel, 14, 0, 1, 1)
        self.label = QtGui.QLabel(self.testFormatTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 16, 0, 1, 3)
        self.actualCodecLabel = QtGui.QLabel(self.testFormatTab)
        self.actualCodecLabel.setObjectName("actualCodecLabel")
        self.gridLayout.addWidget(self.actualCodecLabel, 2, 0, 1, 1)
        self.nearestCodec = QtGui.QLineEdit(self.testFormatTab)
        self.nearestCodec.setEnabled(False)
        self.nearestCodec.setObjectName("nearestCodec")
        self.gridLayout.addWidget(self.nearestCodec, 2, 2, 1, 1)
        self.codecsBox = QtGui.QComboBox(self.testFormatTab)
        self.codecsBox.setObjectName("codecsBox")
        self.gridLayout.addWidget(self.codecsBox, 2, 1, 1, 1)
        self.actualSampleTypeLabel = QtGui.QLabel(self.testFormatTab)
        self.actualSampleTypeLabel.setObjectName("actualSampleTypeLabel")
        self.gridLayout.addWidget(self.actualSampleTypeLabel, 6, 0, 1, 1)
        self.sampleTypesBox = QtGui.QComboBox(self.testFormatTab)
        self.sampleTypesBox.setObjectName("sampleTypesBox")
        self.gridLayout.addWidget(self.sampleTypesBox, 6, 1, 1, 1)
        self.nearestSampleType = QtGui.QLineEdit(self.testFormatTab)
        self.nearestSampleType.setEnabled(False)
        self.nearestSampleType.setObjectName("nearestSampleType")
        self.gridLayout.addWidget(self.nearestSampleType, 6, 2, 1, 1)
        self.tabWidget.addTab(self.testFormatTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.populateTableButton = QtGui.QPushButton(self.tab)
        self.populateTableButton.setObjectName("populateTableButton")
        self.verticalLayout_2.addWidget(self.populateTableButton)
        self.allFormatsTable = QtGui.QTableWidget(self.tab)
        self.allFormatsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.allFormatsTable.setDragDropOverwriteMode(False)
        self.allFormatsTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.allFormatsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.allFormatsTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.allFormatsTable.setWordWrap(False)
        self.allFormatsTable.setCornerButtonEnabled(False)
        self.allFormatsTable.setObjectName("allFormatsTable")
        self.allFormatsTable.setColumnCount(6)
        self.allFormatsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.allFormatsTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.allFormatsTable)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        AudioDevicesBase.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(AudioDevicesBase)
        self.statusbar.setObjectName("statusbar")
        AudioDevicesBase.setStatusBar(self.statusbar)

        self.retranslateUi(AudioDevicesBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AudioDevicesBase)

    def retranslateUi(self, AudioDevicesBase):
        AudioDevicesBase.setWindowTitle(QtGui.QApplication.translate("AudioDevicesBase", "Audio Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.modeLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.modeBox.setItemText(0, QtGui.QApplication.translate("AudioDevicesBase", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.modeBox.setItemText(1, QtGui.QApplication.translate("AudioDevicesBase", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actualLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "<i>Actual Settings</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.nearestLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Nearest Settings</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("AudioDevicesBase", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actualFreqLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Frequency (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.actualChannelLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.actualSampleSizeLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Sample size (bits)", None, QtGui.QApplication.UnicodeUTF8))
        self.actualEndianLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Endianess", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AudioDevicesBase", "Note: an invalid codec \'audio/test\' exists in order to allow an invalid format to be constructed, and therefore to trigger a \'nearest format\' calculation.", None, QtGui.QApplication.UnicodeUTF8))
        self.actualCodecLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.actualSampleTypeLabel.setText(QtGui.QApplication.translate("AudioDevicesBase", "SampleType", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testFormatTab), QtGui.QApplication.translate("AudioDevicesBase", "Test format", None, QtGui.QApplication.UnicodeUTF8))
        self.populateTableButton.setText(QtGui.QApplication.translate("AudioDevicesBase", "Populate table", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.setSortingEnabled(False)
        self.allFormatsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("AudioDevicesBase", "Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("AudioDevicesBase", "Frequency (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("AudioDevicesBase", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("AudioDevicesBase", "Sample type", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("AudioDevicesBase", "Sample size (bits)", None, QtGui.QApplication.UnicodeUTF8))
        self.allFormatsTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("AudioDevicesBase", "Endianness", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("AudioDevicesBase", "All formats", None, QtGui.QApplication.UnicodeUTF8))

