# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backside.ui'
#
# Created: Tue May 27 18:13:23 2008
#      by: PySide UI code generator 4.4.3-snapshot-20080526
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BackSide(object):
    def setupUi(self, BackSide):
        BackSide.setObjectName("BackSide")
        BackSide.resize(378,385)
        self.verticalLayout_2 = QtGui.QVBoxLayout(BackSide)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(BackSide)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label,0,0,1,1)
        self.hostName = QtGui.QLineEdit(self.groupBox)
        self.hostName.setObjectName("hostName")
        self.gridLayout.addWidget(self.hostName,0,1,1,1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2,1,0,1,1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3,2,0,1,1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider = QtGui.QSlider(self.groupBox)
        self.horizontalSlider.setProperty("value",QtCore.QVariant(42))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setProperty("value",QtCore.QVariant(42))
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.gridLayout.addLayout(self.horizontalLayout,2,1,1,1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit,1,1,1,1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(BackSide)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_2)
        self.treeWidget.setObjectName("treeWidget")
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.verticalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(BackSide)
        QtCore.QObject.connect(self.horizontalSlider,QtCore.SIGNAL("valueChanged(int)"),self.spinBox.setValue)
        QtCore.QObject.connect(self.spinBox,QtCore.SIGNAL("valueChanged(int)"),self.horizontalSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(BackSide)
        BackSide.setTabOrder(self.groupBox,self.hostName)
        BackSide.setTabOrder(self.hostName,self.dateTimeEdit)
        BackSide.setTabOrder(self.dateTimeEdit,self.horizontalSlider)
        BackSide.setTabOrder(self.horizontalSlider,self.spinBox)
        BackSide.setTabOrder(self.spinBox,self.groupBox_2)
        BackSide.setTabOrder(self.groupBox_2,self.treeWidget)

    def retranslateUi(self, BackSide):
        BackSide.setWindowTitle(QtGui.QApplication.translate("BackSide", "BackSide", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BackSide", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BackSide", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.hostName.setText(QtGui.QApplication.translate("BackSide", "Pad Navigator Example", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BackSide", "Modified:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BackSide", "Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BackSide", "Other input", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0,QtGui.QApplication.translate("BackSide", "Widgets On Graphics View", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.clear()
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsProxyWidget", None, QtGui.QApplication.UnicodeUTF8))
        item1 = QtGui.QTreeWidgetItem(item)
        item1.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsWidget", None, QtGui.QApplication.UnicodeUTF8))
        item2 = QtGui.QTreeWidgetItem(item1)
        item2.setText(0,QtGui.QApplication.translate("BackSide", "QObject", None, QtGui.QApplication.UnicodeUTF8))
        item3 = QtGui.QTreeWidgetItem(item1)
        item3.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsItem", None, QtGui.QApplication.UnicodeUTF8))
        item4 = QtGui.QTreeWidgetItem(item1)
        item4.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLayoutItem", None, QtGui.QApplication.UnicodeUTF8))
        item5 = QtGui.QTreeWidgetItem(self.treeWidget)
        item5.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsGridLayout", None, QtGui.QApplication.UnicodeUTF8))
        item6 = QtGui.QTreeWidgetItem(item5)
        item6.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLayout", None, QtGui.QApplication.UnicodeUTF8))
        item7 = QtGui.QTreeWidgetItem(item6)
        item7.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLayoutItem", None, QtGui.QApplication.UnicodeUTF8))
        item8 = QtGui.QTreeWidgetItem(self.treeWidget)
        item8.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLinearLayout", None, QtGui.QApplication.UnicodeUTF8))
        item9 = QtGui.QTreeWidgetItem(item8)
        item9.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLayout", None, QtGui.QApplication.UnicodeUTF8))
        item10 = QtGui.QTreeWidgetItem(item9)
        item10.setText(0,QtGui.QApplication.translate("BackSide", "QGraphicsLayoutItem", None, QtGui.QApplication.UnicodeUTF8))

